FROM alpine:3.14.3
LABEL maintainer="gmaris@student.42.fr"

RUN apk update && apk upgrade && apk add --no-cache \
    nginx \
    openssl

RUN mkdir /etc/nginx/ssl
RUN openssl req -x509 \
-newkey rsa:2048 \
-keyout /etc/nginx/ssl/nginx-selfsigned.key \
-out    /etc/nginx/ssl/nginx-selfsigned.crt \
-sha256 \
-nodes   \
-days 365 \
-subj "/C=FR/ST=Paris/L=Paris/O=42/OU=gmaris/CN=gmaris"
RUN openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048

# nginx config
RUN mkdir -p /run/nginx
COPY conf/index.html /var/www/html/index.html
COPY conf/ssl.conf /etc/nginx/http.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]
